-- AlterTable
ALTER TABLE "solutions" ADD COLUMN "timeSpent" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "viewedSolutions" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "similarityScore" DOUBLE PRECISION,
ADD COLUMN "flagCount" INTEGER NOT NULL DEFAULT 0;
